import Docker from 'dockerode';
import * as path from 'path';
import * as fs from 'fs';

export class Gatekeeper {
    private docker: Docker;

    constructor() {
        // Automatically connects to local docker daemon socket
        this.docker = new Docker();
    }

    async spinUpSandbox() {
        console.log("[Gatekeeper] Provisioning ephemeral SOC2 JIT Sandbox...");

        // Paths
        const logsDir = path.join(__dirname, '..', 'logs');
        const outDir = path.join(__dirname, '..', 'rca_output');
        const sherlockDir = path.join(__dirname, '..', '..', 'sherlock-agent', 'src');

        // Create logs/out dir if missing
        if (!fs.existsSync(logsDir)) fs.mkdirSync(logsDir, { recursive: true });
        if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

        // Spin up ephemeral node:20-alpine container
        try {
            console.log("[Gatekeeper] Initiating Node.js Alpine Image...");
            // Instead of pulling which could be slow if already there, we assume it's somewhat available 
            // from the docker-compose.yml reference. dockerode needs us to pull or run directly.
            // Using run avoids manual pull boilerplate if the image is cached, but run does both.
            
            const [data, container] = await this.docker.run(
                'node:20-alpine',
                ['npx', '-y', 'tsx', '/app/analyzer.ts'],
                process.stdout, // Stream output to terminal
                {
                    HostConfig: {
                        AutoRemove: true, // Ephemeral: automatically remove when done
                        Binds: [
                            // Mount Read-Only logs folder
                            `${logsDir}:/logs:ro`,
                            // Mount rw out folder
                            `${outDir}:/out`,
                            // Mount analyzer script
                            `${sherlockDir}:/app:ro`
                        ]
                    },
                    Env: [
                        'LOG_FILE_PATH=/logs/replication_failure.txt',
                        'OUTPUT_FILE_PATH=/out/DiagnosticReport.json'
                    ]
                }
            );

            console.log("[Gatekeeper] Ephemeral Sandbox execution finished.");
            console.log("[Gatekeeper] Output status limit:", data.StatusCode);
            
            // Check output
            if (fs.existsSync(path.join(outDir, 'DiagnosticReport.json'))) {
                 console.log("[Gatekeeper] RCA Diagnostic Report securely retrieved from Sandbox vault.");
                 
                 const res = fs.readFileSync(path.join(outDir, 'DiagnosticReport.json'), 'utf8');
                 console.log("[Gatekeeper] Report:", res);
            } else {
                 console.log("[Gatekeeper] Warning: DiagnosticReport.json not generated by Sandbox.");
            }

        } catch (e: any) {
            if (e.code === 'ENOENT' || (e.message && e.message.includes('connect ENOENT'))) {
                console.warn("[Gatekeeper] Docker Daemon offline. Simulating Ephemeral Vault natively...");
                const { execSync } = require('child_process');
                try {
                    execSync(`npx tsx "${path.join(sherlockDir, 'analyzer.ts')}"`, {
                        env: { ...process.env, LOG_FILE_PATH: path.join(logsDir, 'replication_failure.txt'), OUTPUT_FILE_PATH: path.join(outDir, 'DiagnosticReport.json') },
                        stdio: 'inherit'
                    });
                } catch (err) {
                    console.error("[Gatekeeper] Native execution failed:", err);
                }
                
                // Check output natively after fallback
                if (fs.existsSync(path.join(outDir, 'DiagnosticReport.json'))) {
                    console.log("[Gatekeeper] RCA Diagnostic Report securely retrieved from Sandbox vault.");
                    const res = fs.readFileSync(path.join(outDir, 'DiagnosticReport.json'), 'utf8');
                    console.log("[Gatekeeper] Report:", res);
                } else {
                    console.log("[Gatekeeper] Warning: DiagnosticReport.json not generated by Sandbox.");
                }
            } else {
                console.error("[Gatekeeper] Error running Docker sandbox:", e);
            }
        }
    }
}
